name: CI - API Monitoramento

on:
  push:
    branches: [ "feature/ci", "feature/alertas-discord" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Rodar testes
      run: |
        python -m unittest discover

    - name: Python Lint Code Scanning Action
      uses: advanced-security/python-lint-code-scanning-action@v1.1.3
      with:
        linter: pylint

    #  ALERTA SUCESSO
    - name: Notificar Discord - Sucesso
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
        -d "{\"content\": \" CI executado com SUCESSO no repositório!\"}" \
        ${{ secrets.DISCORD_WEBHOOK }}

    # ALERTA FALHA
    - name: Notificar Discord - Falha
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
        -d "{\"content\": \" CI FALHOU! Verifique o GitHub Actions.\"}" \
        ${{ secrets.DISCORD_WEBHOOK }}